# Site settings
title: Kiyah Mitchell
description: A portfolio with creative projects.
url: "https://kiyahmitchell.github.io"
baseurl: "" # Leave empty if your site is at the root

# Author settings
author:
  name: "Kiyah Mitchell"
  email: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Permalink settings
permalink: pretty

